server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    rest:
      base-path: /api
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: select 1
    password: dada123456
    url: jdbc:mysql://localhost:3306/chicken?useSSL=false&characterEncoding=utf8
    username: adonika
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
security:
  oauth2:
    resource:
      id: chicken_rest_api