# Server
server:
  port: 8080
  servlet:
    context-path: /

# Logger
logging: 
  level: 
    org: 
      springframework: 
        security: DEBUG
  path: /logs

# Spring
spring: 
  data:
    rest:
      base-path: /api
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: select 1
    password: dada123456
    url: jdbc:mysql://localhost:3306/chicken?useSSL=false&characterEncoding=utf8
    username: adonika
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
#        default_batch_fetch_size: 20 # 자식객체 query 날리는걸 in 구문으로 변경해줌
    show-sql: true
security:
  oauth2: 
#    client: 
#      clientId: trusted-app
#      clientSecret: secret
#      accessTokenUri: http://localhost:${server.port}/oauth/token
#      userAuthorizationUri: http://localhost:${server.port}/oauth/authorize
#      tokenName: Authorization
#      authenticationScheme: query
#      clientAuthenticationScheme: form
    resource:
      id: chicken_rest_api
#      userInfoUri: http://localhost:${server.port}/me
#      jwt: 
#        key-uri: https://localhost:${server.port}/oauth/token_key
